//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatosDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarcaModeloVehiculo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MarcaModeloVehiculo()
        {
            this.Vehiculo = new HashSet<Vehiculo>();
        }
    
        public int IdMarca { get; set; }
        public int IdModelo { get; set; }
    
        public virtual MarcaVehiculo MarcaVehiculo { get; set; }
        public virtual ModeloVehiculo ModeloVehiculo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vehiculo> Vehiculo { get; set; }
    }
}
